# Generated by Django 5.2.7 on 2025-10-07 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_roi', models.DecimalField(decimal_places=2, help_text='Daily ROI in percentage', max_digits=5)),
                ('duration_days', models.PositiveIntegerField()),
                ('total_return', models.DecimalField(decimal_places=2, help_text='Total ROI + Capital', max_digits=5)),
                ('compound_interest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('expected_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investments', to='investments.investmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
