# Generated by Django 5.2.7 on 2025-10-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_remove_deposit_is_confirmed_deposit_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
